version: '3.1'
services:
  web:
    image: odoo:17.0
    ports:
      - "8069:8069"
    environment:
      - ADDONS_PATH=/mnt/extra-addons/17.0,/usr/lib/python3/dist-packages/odoo/addons
    volumes:
      - /opt/odoo/config:/etc/odoo
      - /opt/odoo/addons/17.0:/mnt/extra-addons/17.0
    command: ["odoo","-c","/etc/odoo/odoo.conf","-i","custom_auto_login,custom_logout,custom_login_ccp"]